version: '{build}'

skip_tags: true

environment:
  matrix:    
    - ruby_version: "19"
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install bundler --no-document -v 1.10.5
  - bundle install --retry=3

test_script:
  - cp example.config.rb config.rb
  - bundle exec rake

build: off
